import { richTextWrapperName } from "./names.ts";
import { SUPPORTED_TAGS } from "./tag-set.ts";
import type { RichTextStyleTable } from "./types.ts";

function classNamesFor(table: RichTextStyleTable): string[] {
  const classes: string[] = [];
  for (const tag of SUPPORTED_TAGS) {
    const style = table[tag];
    if (style === undefined) continue;
    for (const [prop, value] of Object.entries(style.props)) {
      classes.push(`[&_${tag}]:[${prop}:${value.trim().replace(/\s+/g, "_")}]`);
    }
  }
  return classes;
}

export function emitRichTextWrapper(fieldName: string, table: RichTextStyleTable): string {
  const name = richTextWrapperName(fieldName);
  const className = classNamesFor(table).join(" ");
  return `import { PortableText, type PortableTextComponents } from "@portabletext/react";
import type { PortableTextBlock } from "@portabletext/types";

import { urlFor } from "@/sanity/image";

// Auto-generated richText wrapper — per-tag styles measured on the reference page.
// Do not edit by hand; regenerated by synth --richtext-accept.

const components: PortableTextComponents = {
  types: {
    image: ({ value }) => <img src={urlFor(value).url()} alt={value?.alt ?? ""} />,
  },
};

export default function ${name}({ value, ...rest }: { value: PortableTextBlock[] } & Record<string, unknown>) {
  return (
    <div className=${JSON.stringify(className)} {...rest}>
      <PortableText value={value} components={components} />
    </div>
  );
}
`;
}
