export const DISCOVERY_STEP_PREFIX = "discovery";

export const DISCOVERY_GLOBALS_SCHEMA_STEP_ID = `${DISCOVERY_STEP_PREFIX}:globals:schema` as const;
export const DISCOVERY_GLOBALS_SUBJECT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:globals:subject` as const;
export const DISCOVERY_GLOBALS_JUDGE_STEP_ID = `${DISCOVERY_STEP_PREFIX}:globals:judge` as const;
export const DISCOVERY_GLOBALS_ACCEPT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:globals:accept` as const;

export const DISCOVERY_BLOCKS_SCHEMA_STEP_ID = `${DISCOVERY_STEP_PREFIX}:blocks:schema` as const;
export const DISCOVERY_BLOCKS_SUBJECT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:blocks:subject` as const;
export const DISCOVERY_BLOCKS_JUDGE_STEP_ID = `${DISCOVERY_STEP_PREFIX}:blocks:judge` as const;
export const DISCOVERY_BLOCKS_ACCEPT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:blocks:accept` as const;

export const DISCOVERY_DEDUP_SCHEMA_STEP_ID = `${DISCOVERY_STEP_PREFIX}:dedup:schema` as const;
export const DISCOVERY_DEDUP_SUBJECT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:dedup:subject` as const;
export const DISCOVERY_DEDUP_JUDGE_STEP_ID = `${DISCOVERY_STEP_PREFIX}:dedup:judge` as const;
export const DISCOVERY_DEDUP_ACCEPT_STEP_ID = `${DISCOVERY_STEP_PREFIX}:dedup:accept` as const;

export const DISCOVERY_COLLECTIONS_STEP_ID = `${DISCOVERY_STEP_PREFIX}:collections` as const;
export const DISCOVERY_FINALIZE_STEP_ID = `${DISCOVERY_STEP_PREFIX}:finalize` as const;

export const DISCOVERY_STEP_IDS = [
  DISCOVERY_GLOBALS_SCHEMA_STEP_ID,
  DISCOVERY_GLOBALS_SUBJECT_STEP_ID,
  DISCOVERY_GLOBALS_JUDGE_STEP_ID,
  DISCOVERY_GLOBALS_ACCEPT_STEP_ID,
  DISCOVERY_BLOCKS_SCHEMA_STEP_ID,
  DISCOVERY_BLOCKS_SUBJECT_STEP_ID,
  DISCOVERY_BLOCKS_JUDGE_STEP_ID,
  DISCOVERY_BLOCKS_ACCEPT_STEP_ID,
  DISCOVERY_DEDUP_SCHEMA_STEP_ID,
  DISCOVERY_DEDUP_SUBJECT_STEP_ID,
  DISCOVERY_DEDUP_JUDGE_STEP_ID,
  DISCOVERY_DEDUP_ACCEPT_STEP_ID,
  DISCOVERY_COLLECTIONS_STEP_ID,
  DISCOVERY_FINALIZE_STEP_ID,
] as const;
